name: Security Scan - Secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Allow the action to read the repository content

jobs:
  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for gitleaks

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          # Optional: Add a GitHub token for organizational checks if needed.
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Point to a custom gitleaks config if you have one
          # GITLEAKS_CONFIG: .gitleaks.toml
          # Set this to true if you want the Action to fail when leaks are found
          GITLEAKS_ENABLE_FAIL: true
